"use client";
import { useEffect, useMemo, useState } from "react";
import { Columns3, List, Search } from "lucide-react";
import { apiPut, fetchAll } from "@/lib/api";
import { money } from "@/components/ResourceWorkspace";
import DealsWorkspace from "@/components/DealsWorkspace";

type Deal = { dealId: number; title: string; accountId: number | null; contactId: number | null; dealStageId: number | null; dealOwnerId: number | null; value: number | null; expectedCloseDate: string | null; dealStatus: "open" | "won" | "lost"; closingNote: string | null };
type Stage = { dealStageId: number; stage: string; probability: number; displayOrder: number; active: boolean; isActive?: boolean };

export default function DealsPage() { return <DealsWorkspace/>; }

export function LegacyDealsPage() {
  const [deals, setDeals] = useState<Deal[]>([]); const [stages, setStages] = useState<Stage[]>([]); const [view, setView] = useState<"table"|"kanban">("kanban"); const [query, setQuery] = useState(""); const [error, setError] = useState(""); const [loading, setLoading] = useState(true);
  useEffect(() => { Promise.all([fetchAll<Deal>("/deals"), fetch("/api/backend/deal-stages", { cache: "no-store" }).then((r) => { if (!r.ok) throw new Error("Unable to load stages"); return r.json(); })]).then(([dealData, stageData]) => { setDeals(dealData); setStages(stageData.sort((a: Stage,b: Stage) => a.displayOrder-b.displayOrder)); }).catch((e) => setError(e.message)).finally(() => setLoading(false)); }, []);
  const visible = useMemo(() => deals.filter((deal) => deal.title.toLowerCase().includes(query.toLowerCase())), [deals, query]);
  async function move(deal: Deal, stageId: number) { if (deal.dealStageId === stageId) return; const previous = deals; setDeals(deals.map((item) => item.dealId === deal.dealId ? { ...item, dealStageId: stageId } : item)); try { await apiPut(`/deals/${deal.dealId}`, { ...deal, dealStageId: stageId }); } catch (e) { setDeals(previous); setError(e instanceof Error ? e.message : "Unable to move deal."); } }
  return <div className="space-y-5"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><div className="flex items-center gap-3"><h1 className="text-2xl font-semibold tracking-tight text-slate-950">Deals</h1>{!loading && <span className="rounded-full border border-slate-200 bg-white px-2.5 py-1 text-xs font-medium text-slate-500">{deals.length}</span>}</div><p className="mt-1.5 text-sm text-slate-500">Track every opportunity from first conversation to close.</p></div><div className="flex rounded-md border border-slate-200 bg-white p-1"><button onClick={() => setView("table")} className={`flex items-center gap-2 rounded px-3 py-1.5 text-sm ${view === "table" ? "bg-blue-50 font-semibold text-blue-700" : "text-slate-600"}`}><List size={16}/>Table</button><button onClick={() => setView("kanban")} className={`flex items-center gap-2 rounded px-3 py-1.5 text-sm ${view === "kanban" ? "bg-blue-50 font-semibold text-blue-700" : "text-slate-600"}`}><Columns3 size={16}/>Kanban</button></div></div>
  {error && <div className="rounded-xl border border-rose-200 bg-rose-50 p-4 text-sm text-rose-700">{error}</div>}
  <label className="relative block max-w-md"><Search className="absolute left-3 top-2.5 text-slate-400" size={17}/><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search deals..." className="w-full rounded-md border border-slate-300 bg-white py-2 pl-9 pr-3 text-sm outline-none focus:border-blue-500 focus:ring-2 focus:ring-blue-100"/></label>
  {loading ? <div className="rounded-xl border bg-white p-12 text-center text-sm text-slate-500">Loading pipeline...</div> : view === "table" ? <div className="overflow-x-auto rounded-xl border border-slate-200 bg-white"><table className="w-full min-w-[850px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="px-4 py-3">Deal</th><th className="px-4 py-3">Stage</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Value</th><th className="px-4 py-3">Expected close</th><th className="px-4 py-3">Owner</th></tr></thead><tbody className="divide-y">{visible.map((deal) => <tr key={deal.dealId}><td className="px-4 py-4 font-medium text-slate-900">{deal.title}</td><td className="px-4 py-4">{stages.find((s) => s.dealStageId === deal.dealStageId)?.stage || "-"}</td><td className="px-4 py-4 capitalize">{deal.dealStatus}</td><td className="px-4 py-4">{money(deal.value)}</td><td className="px-4 py-4">{deal.expectedCloseDate ? new Date(deal.expectedCloseDate).toLocaleDateString("en-IN") : "-"}</td><td className="px-4 py-4">#{deal.dealOwnerId || "-"}</td></tr>)}</tbody></table></div> : <div className="flex gap-4 overflow-x-auto pb-4">{stages.map((stage) => { const stageDeals = visible.filter((deal) => deal.dealStageId === stage.dealStageId); return <section key={stage.dealStageId} onDragOver={(e) => e.preventDefault()} onDrop={(e) => { const deal = deals.find((item) => item.dealId === Number(e.dataTransfer.getData("dealId"))); if (deal) move(deal, stage.dealStageId); }} className="w-72 shrink-0 rounded-xl bg-slate-100 p-3"><div className="mb-3 flex items-start justify-between"><div><h2 className="font-semibold text-slate-800">{stage.stage}</h2><p className="mt-0.5 text-xs text-slate-500">{stageDeals.length} deals · {money(stageDeals.reduce((sum,d) => sum + Number(d.value || 0),0))}</p></div><span className="rounded-full bg-white px-2 py-1 text-xs text-slate-500">{stage.probability}%</span></div><div className="space-y-3">{stageDeals.map((deal) => <article key={deal.dealId} draggable onDragStart={(e) => e.dataTransfer.setData("dealId", String(deal.dealId))} className="cursor-grab rounded-lg border border-slate-200 bg-white p-4 shadow-sm active:cursor-grabbing"><h3 className="font-semibold text-slate-900">{deal.title}</h3><p className="mt-3 text-lg font-semibold text-slate-800">{money(deal.value)}</p><div className="mt-3 flex justify-between text-xs text-slate-500"><span className="capitalize">{deal.dealStatus}</span><span>{deal.expectedCloseDate ? new Date(deal.expectedCloseDate).toLocaleDateString("en-IN") : "No close date"}</span></div></article>)}{stageDeals.length === 0 && <div className="rounded-lg border border-dashed border-slate-300 p-5 text-center text-xs text-slate-500">Drop a deal here</div>}</div></section>; })}</div>}
  </div>;
}
