
create table accounts (
                          acc_id integer generated by default as identity,
                          acc_owner_id bigint not null,
                          created_at timestamp(6),
                          updated_at timestamp(6),
                          account_name varchar(255) not null,
                          industry varchar(255) not null check ((industry in ('Technology','Banking','Healthcare','Education','Retail','Manufacturing','Real_Estate','Telecommunication','Others'))),
                          phone_number varchar(255),
                          website varchar(255),
                          primary key (acc_id)
);

create table activity (
                          deal_id integer,
                          id integer generated by default as identity,
                          lead_id integer,
                          completed_at timestamp(6),
                          created_at timestamp(6),
                          created_by bigint not null,
                          due_at timestamp(6),
                          activity_type varchar(255) not null check ((activity_type in ('Call','Email','Meeting','Comment','Task'))),
                          status varchar(255) not null,
                          subject varchar(255) not null,
                          primary key (id)
);

create table audit_logs (
                            audit_id integer generated by default as identity,
                            created_at timestamp(6) not null,
                            user_id bigint not null,
                            action varchar(50) not null,
                            entity_id varchar(50),
                            entity_type varchar(50) not null,
                            primary key (audit_id)
);

create table contact (
                         account_id integer not null,
                         contact_id integer generated by default as identity,
                         contact_owner_id bigint not null,
                         created_at timestamp(6),
                         updated_at timestamp(6),
                         "Job Title" varchar(255),
                         email varchar(255) not null unique,
                         lifecycle_status varchar(255) not null check ((lifecycle_status in ('Customer','Active','Inactive','Prospect'))),
                         name varchar(255) not null,
                         phone_number varchar(255),
                         primary key (contact_id)
);

create table deal (
                      account_id integer not null,
                      contact_id integer not null,
                      deal_id integer generated by default as identity,
                      deal_stage_id integer not null,
                      value numeric(38,2),
                      created_at timestamp(6),
                      deal_owner_id bigint not null,
                      expected_close_date timestamp(6),
                      updated_at timestamp(6),
                      "Closing Note" varchar(255),
                      deal_status varchar(255) default open not null check ((deal_status in ('open','won','lost'))),
                      title varchar(255) not null,
                      primary key (deal_id)
);

create table deal_stage (
                            deal_stage_id integer generated by default as identity,
                            display_order integer not null,
                            is_active boolean not null,
                            probability integer not null,
                            stage varchar(255) not null,
                            primary key (deal_stage_id)
);

create table deal_stage_history (
                                    deal_id integer not null,
                                    history_id integer generated by default as identity,
                                    changed_at timestamp(6),
                                    changed_by bigint not null,
                                    from_stage varchar(255) not null,
                                    to_stage varchar(255) not null,
                                    primary key (history_id)
);

create table leads (
                       expected_value numeric(38,2),
                       lead_id integer generated by default as identity,
                       owner_id bigint not null,
                       company_name varchar(255),
                       email varchar(255) not null unique,
                       lead_rating varchar(255) check ((lead_rating in ('Hot','Warm','Cold'))),
                       name varchar(255) not null,
                       notes varchar(255),
                       phone_number varchar(255),
                       salutation varchar(255) check ((salutation in ('Mr','Ms','Mrs','Dr','Prof'))),
                       source varchar(255) default Website check ((source in ('Website','Referral','Social_Media','Campaign'))),
                       status varchar(255) default New not null check ((status in ('New','Qualified','Contacted','Unqualified','Converted'))),
                       primary key (lead_id)
);

create table notification (
                              notification_id integer generated by default as identity,
                              "created at" timestamp(6) not null,
                              "sent at" timestamp(6) not null,
                              user_id bigint not null,
                              message varchar(500) not null,
                              notification_status varchar(255) not null check ((notification_status in ('Unread','Pending','Delivered','Read','Failed'))),
                              notification_type varchar(255),
                              primary key (notification_id)
);

create table permissions (
                             permission_id bigint generated by default as identity,
                             description varchar(255),
                             permission_name varchar(255) not null unique,
                             primary key (permission_id)
);

create table role_permissions (
                                  permission_id bigint not null,
                                  role_id bigint not null,
                                  role_permission_id bigint generated by default as identity,
                                  primary key (role_permission_id),
                                  unique (role_id, permission_id)
);

create table roles (
                       role_id bigint generated by default as identity,
                       description varchar(255),
                       role_name varchar(255) not null unique check ((role_name in ('ADMIN','SALES_MANAGER','SALES_EXECUTIVE'))),
                       primary key (role_id)
);

create table users (
                       is_active boolean default true not null,
                       created_at timestamp(6) not null,
                       role_id bigint not null,
                       uid bigint not null,
                       updated_at timestamp(6),
                       email varchar(255) not null unique,
                       name varchar(255) not null,
                       password_hash varchar(255) not null,
                       primary key (uid)
);

create index idx_account_owner
    on accounts (acc_owner_id);

create index idx_account_name
    on accounts (account_name);

create index idx_account_industry
    on accounts (industry);

create index idx_contact_account
    on contact (account_id);

create index idx_contact_owner
    on contact (contact_owner_id);

create index idx_lead_owner
    on leads (owner_id);

create index idx_lead_email
    on leads (email);

create index idx_lead_status
    on leads (status);

create index idx_lead_source
    on leads (source);

create index idx_notification_user_status
    on notification (user_id, status);

alter table if exists accounts
    add constraint FK8s5gjic37b79muigna09ty4od
    foreign key (acc_owner_id)
    references users;

alter table if exists activity
    add constraint FK6fel5mlh9psxad5sp7n98pu0j
    foreign key (deal_id)
    references deal;

alter table if exists activity
    add constraint FKd5ynb9njqsth8jrh4fo0in2fu
    foreign key (lead_id)
    references leads;

alter table if exists activity
    add constraint FKjl2l037106rgpmoachn6ubkma
    foreign key (created_by)
    references users;

alter table if exists audit_logs
    add constraint FKjs4iimve3y0xssbtve5ysyef0
    foreign key (user_id)
    references users;

alter table if exists contact
    add constraint FKg9qenj6slk4clat5tahb79b3l
    foreign key (account_id)
    references accounts;

alter table if exists contact
    add constraint FK627qe1p2q7rriqc8940p5hguf
    foreign key (contact_owner_id)
    references users;

alter table if exists deal
    add constraint FKti7x75bu7ut6xf0qa06v8qrpo
    foreign key (account_id)
    references accounts;

alter table if exists deal
    add constraint FKtolypiptt0165t7a2cwwg7p17
    foreign key (contact_id)
    references contact;

alter table if exists deal
    add constraint FKhp4m8o2dys5j2kyht1sjo9k9q
    foreign key (deal_stage_id)
    references deal_stage;

alter table if exists deal
    add constraint FKi3lvytoaimcsdfb0y6hlxbsyt
    foreign key (deal_owner_id)
    references users;

alter table if exists deal_stage_history
    add constraint FK44jee1kr522uuwmcoit644bwl
    foreign key (deal_id)
    references deal;

alter table if exists deal_stage_history
    add constraint FKmeo6gw1ioc9s8ihhivvilpdb
    foreign key (changed_by)
    references users;

alter table if exists leads
    add constraint FK6atlkrs3i0qaviw1valk4cspd
    foreign key (owner_id)
    references users;

alter table if exists notification
    add constraint FKnk4ftb5am9ubmkv1661h15ds9
    foreign key (user_id)
    references users;

alter table if exists role_permissions
    add constraint FKegdk29eiy7mdtefy5c7eirr6e
    foreign key (permission_id)
    references permissions;

alter table if exists role_permissions
    add constraint FKn5fotdgk8d1xvo8nav9uv3muc
    foreign key (role_id)
    references roles;

alter table if exists users
    add constraint FKp56c1712k691lhsyewcssf40f
    foreign key (role_id)
    references roles;
