
CREATE TABLE users (
                       uid VARCHAR(10) PRIMARY KEY,
                       name VARCHAR(255) NOT NULL,
                       email VARCHAR(255) NOT NULL UNIQUE,
                       password_hash VARCHAR(255) NOT NULL,
                       role VARCHAR(255) NOT NULL,
                       is_active BOOLEAN NOT NULL DEFAULT TRUE,
                       created_at TIMESTAMP NOT NULL,
                       updated_at TIMESTAMP
);

CREATE TABLE "Accounts" (
                            acc_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            account_name VARCHAR(255) NOT NULL,
                            industry VARCHAR(255) NOT NULL,
                            phone_number VARCHAR(255),
                            "Website" VARCHAR(255),
                            created_at TIMESTAMP,
                            updated_at TIMESTAMP,
                            acc_owner_id VARCHAR(10) NOT NULL
);

CREATE TABLE "Contact" (
                           contact_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           name VARCHAR(255) NOT NULL,
                           email VARCHAR(255) NOT NULL UNIQUE,
                           "LifecycleStatus" VARCHAR(255) NOT NULL,
                           phone_number VARCHAR(255),
                           "Job Title" VARCHAR(255),
                           created_at TIMESTAMP,
                           updated_at TIMESTAMP,
                           contact_owner_id VARCHAR(10) NOT NULL,
                           account_id INTEGER NOT NULL
);

CREATE TABLE "Leads" (
                         lead_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         "Salutation" VARCHAR(255),
                         name VARCHAR(255) NOT NULL,
                         status VARCHAR(255) NOT NULL,
                         email VARCHAR(255) NOT NULL UNIQUE,
                         phone_number VARCHAR(255),
                         company_name VARCHAR(255),
                         source VARCHAR(255),
                         notes VARCHAR(255),
                         lead_rating VARCHAR(255),
                         expected_value NUMERIC(19,2),
                         owner_id VARCHAR(10) NOT NULL
);

CREATE TABLE "DealStage" (
                             deal_stage_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             "Stage" VARCHAR(255) NOT NULL,
                             display_order INTEGER NOT NULL UNIQUE,
                             probability INTEGER NOT NULL,
                             is_active BOOLEAN NOT NULL,
                             CONSTRAINT chk_dealstage_probability
                                 CHECK (probability BETWEEN 0 AND 100)
);

CREATE TABLE "Deal" (
                        deal_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        "Title" VARCHAR(255) NOT NULL,
                        "DealStatus" VARCHAR(255) NOT NULL,
                        expected_close_date TIMESTAMP,
                        "Value" NUMERIC(19,2),
                        "Closing Note" VARCHAR(255),
                        created_at TIMESTAMP,
                        updated_at TIMESTAMP,
                        deal_owner_id VARCHAR(10) NOT NULL,
                        deal_stage_id INTEGER NOT NULL,
                        account_id INTEGER NOT NULL,
                        contact_id INTEGER NOT NULL
);

CREATE TABLE "DealStage_History" (
                                     history_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     deal_id INTEGER NOT NULL,
                                     from_stage VARCHAR(255) NOT NULL,
                                     to_stage VARCHAR(255) NOT NULL,
                                     changed_at TIMESTAMP,
                                     "Changed_By" VARCHAR(10) NOT NULL
);

CREATE TABLE "Activity" (
                            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            "ActivityType" VARCHAR(255) NOT NULL,
                            "Subject" VARCHAR(255) NOT NULL,
                            "Status" VARCHAR(255) NOT NULL,
                            due_at TIMESTAMP,
                            completed_at TIMESTAMP,
                            created_at TIMESTAMP,
                            deal_id INTEGER,
                            lead_id INTEGER,
                            created_by VARCHAR(10) NOT NULL
);

CREATE TABLE "Notification" (
                                notification_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                user_id VARCHAR(10) NOT NULL,
                                "Notification_Type" VARCHAR(255),
                                message VARCHAR(500) NOT NULL,
                                "NotificationStatus" VARCHAR(255) NOT NULL,
                                "created at" TIMESTAMP NOT NULL,
                                "sent at" TIMESTAMP NOT NULL
);

CREATE TABLE audit_logs (
                            audit_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            user_id VARCHAR(10) NOT NULL,
                            action VARCHAR(50) NOT NULL,
                            entity_type VARCHAR(50) NOT NULL,
                            entity_id VARCHAR(50),
                            created_at TIMESTAMP NOT NULL
);

-- Foreign key constraints
-- Added after all tables exist so table creation order is simpler.
ALTER TABLE "Accounts"
    ADD CONSTRAINT fk_accounts_owner
        FOREIGN KEY (acc_owner_id) REFERENCES users(uid);

ALTER TABLE "Contact"
    ADD CONSTRAINT fk_contact_owner
        FOREIGN KEY (contact_owner_id) REFERENCES users(uid);

ALTER TABLE "Contact"
    ADD CONSTRAINT fk_contact_account
        FOREIGN KEY (account_id) REFERENCES "Accounts"(acc_id);

ALTER TABLE "Leads"
    ADD CONSTRAINT fk_leads_owner
        FOREIGN KEY (owner_id) REFERENCES users(uid);

ALTER TABLE "Deal"
    ADD CONSTRAINT fk_deal_owner
        FOREIGN KEY (deal_owner_id) REFERENCES users(uid);

ALTER TABLE "Deal"
    ADD CONSTRAINT fk_deal_stage
        FOREIGN KEY (deal_stage_id) REFERENCES "DealStage"(deal_stage_id);

ALTER TABLE "Deal"
    ADD CONSTRAINT fk_deal_account
        FOREIGN KEY (account_id) REFERENCES "Accounts"(acc_id);

ALTER TABLE "Deal"
    ADD CONSTRAINT fk_deal_contact
        FOREIGN KEY (contact_id) REFERENCES "Contact"(contact_id);

ALTER TABLE "DealStage_History"
    ADD CONSTRAINT fk_dealstage_history_deal
        FOREIGN KEY (deal_id) REFERENCES "Deal"(deal_id);

ALTER TABLE "DealStage_History"
    ADD CONSTRAINT fk_dealstage_history_user
        FOREIGN KEY ("Changed_By") REFERENCES users(uid);

ALTER TABLE "Activity"
    ADD CONSTRAINT fk_activity_deal
        FOREIGN KEY (deal_id) REFERENCES "Deal"(deal_id);

ALTER TABLE "Activity"
    ADD CONSTRAINT fk_activity_lead
        FOREIGN KEY (lead_id) REFERENCES "Leads"(lead_id);

ALTER TABLE "Activity"
    ADD CONSTRAINT fk_activity_user
        FOREIGN KEY (created_by) REFERENCES users(uid);

ALTER TABLE "Notification"
    ADD CONSTRAINT fk_notification_user
        FOREIGN KEY (user_id) REFERENCES users(uid);

ALTER TABLE audit_logs
    ADD CONSTRAINT fk_audit_logs_user
        FOREIGN KEY (user_id) REFERENCES users(uid);


-- Foreign-key and commonly filtered-column indexes.
-- PK and UNIQUE columns already receive indexes from PostgreSQL.
CREATE INDEX idx_accounts_owner
    ON "Accounts"(acc_owner_id);

CREATE INDEX idx_contact_owner
    ON "Contact"(contact_owner_id);

CREATE INDEX idx_contact_account
    ON "Contact"(account_id);

CREATE INDEX idx_leads_owner
    ON "Leads"(owner_id);

CREATE INDEX idx_leads_status
    ON "Leads"(status);

CREATE INDEX idx_deal_owner
    ON "Deal"(deal_owner_id);

CREATE INDEX idx_deal_stage
    ON "Deal"(deal_stage_id);

CREATE INDEX idx_deal_account
    ON "Deal"(account_id);

CREATE INDEX idx_deal_contact
    ON "Deal"(contact_id);

CREATE INDEX idx_dealstage_history_deal
    ON "DealStage_History"(deal_id);

CREATE INDEX idx_dealstage_history_changed_by
    ON "DealStage_History"("Changed_By");

CREATE INDEX idx_activity_deal
    ON "Activity"(deal_id);

CREATE INDEX idx_activity_lead
    ON "Activity"(lead_id);

CREATE INDEX idx_activity_created_by
    ON "Activity"(created_by);

CREATE INDEX idx_notification_user
    ON "Notification"(user_id);

CREATE INDEX idx_audit_logs_user
    ON audit_logs(user_id);
