"use client";
import { useEffect, useState } from "react";
import { apiGet } from "@/lib/api";
import { money } from "@/components/ResourceWorkspace";
import BreakdownCard from "@/components/BreakdownCard";
type Performance = { userId: number; name: string; wonDeals: number; revenue: number };
export default function ReportsPage() {
 const [data,setData]=useState<{leads:Record<string,number>; deals:Record<string,number>; values:Record<string,number>; performance:Performance[]}|null>(null); const [error,setError]=useState("");
 useEffect(()=>{Promise.all([apiGet<Record<string,number>>("/api/reports/leads/status"),apiGet<Record<string,number>>("/api/reports/deals/status"),apiGet<Record<string,number>>("/api/reports/deals/value"),apiGet<Performance[]>("/api/reports/sales-performance")]).then(([leads,deals,values,performance])=>setData({leads,deals,values,performance})).catch((e)=>setError(e.status===403?"Reports are available to administrators and sales managers.":e.message));},[]);
 const items=(values:Record<string,number>)=>Object.entries(values).map(([label,value])=>({label,value:Number(value)}));
 return <div className="space-y-5"><div><h1 className="text-2xl font-semibold tracking-tight">Reports</h1><p className="mt-1.5 text-sm text-slate-500">Live pipeline and sales results from the CRM.</p></div>{error&&<div className="rounded-lg border border-amber-200 bg-amber-50 p-4 text-sm text-amber-800">{error}</div>}{!data&&!error?<div className="grid gap-4 lg:grid-cols-3">{[1,2,3].map(item=><div key={item} className="h-52 animate-pulse rounded-lg border border-slate-200 bg-white p-5"><div className="h-4 w-24 rounded bg-slate-100"/><div className="mt-3 h-3 w-40 rounded bg-slate-100"/><div className="mt-10 h-2.5 rounded bg-slate-100"/></div>)}</div>:data&&<><div className="grid items-start gap-4 lg:grid-cols-3"><BreakdownCard title="Leads" subtitle="Current lead distribution by status" items={items(data.leads)}/><BreakdownCard title="Deals" subtitle="Current deal distribution by status" items={items(data.deals)}/><BreakdownCard title="Deal Value" subtitle="Pipeline value grouped by status" items={items(data.values)} formatValue={money} totalLabel="Combined"/></div><section className="overflow-hidden rounded-lg border border-slate-200 bg-white"><div className="border-b border-slate-200 px-5 py-4"><h2 className="text-sm font-semibold text-slate-900">Sales performance</h2><p className="mt-1 text-xs text-slate-500">Won deals and recognized revenue by salesperson</p></div>{data.performance.length===0?<div className="px-5 py-10 text-center"><p className="text-sm font-medium text-slate-600">No sales performance data</p><p className="mt-1 text-xs text-slate-400">Won-deal results will appear here.</p></div>:<div className="overflow-x-auto"><table className="w-full min-w-[560px] text-sm"><thead className="border-b border-slate-200 bg-slate-50/80 text-left text-xs text-slate-500"><tr><th className="px-5 py-3 font-semibold">Salesperson</th><th className="px-5 py-3 font-semibold">Won deals</th><th className="px-5 py-3 font-semibold">Revenue</th></tr></thead><tbody className="divide-y divide-slate-100">{data.performance.map((row)=><tr key={row.userId} className="hover:bg-blue-50/30"><td className="px-5 py-3.5 font-medium text-slate-900">{row.name}</td><td className="px-5 py-3.5 text-slate-600">{row.wonDeals}</td><td className="px-5 py-3.5 font-medium text-slate-800">{money(row.revenue)}</td></tr>)}</tbody></table></div>}</section></>}</div>;
}
